import os
import gc
import shutil
import re
import glob
import numpy as np
import pandas as pd
import tifffile as tiff
from datetime import datetime, timedelta
import spectral.io.envi as envi
from cropsense_config import TOUCAN_PATTERN, SILIOS_WAVELENGTHS
from cropsense_database import sanitize_for_mongo, get_or_create_capture_event



def parse_colorshades_manifest(txt_filepath):
    """
    Parses the .txt manifest generated by Color Shades to extract technical metadata
    including real wavelengths and normalization coefficients.
    """
    meta = {
        "camera_sn": "Unknown", 
        "exposure": 1.0, 
        "wavelengths": [],    
        "coefficients": []    
    }
    
    if not os.path.exists(txt_filepath):
        return meta

    try:
        with open(txt_filepath, 'r') as f:
            content = f.readlines()
            
        for line in content:
            # Serial Number
            if "Camera SN" in line:
                meta["camera_sn"] = line.split(":")[-1].strip()
            
            # Exposure (remove " ms" unit)
            if "Exposure" in line:
                val = line.split(":")[-1].strip().replace(" ms", "")
                try: meta["exposure"] = float(val)
                except: pass
                
            # Real Wavelengths (e.g. 411, 463...)
            if "Filter's centering (nm)" in line:
                raw_vals = line.split(":")[-1].strip().split()
                meta["wavelengths"] = [int(x) for x in raw_vals]
                
            # Channel Coefficients
            if "Coefficients channel normalizer" in line:
                raw_vals = line.split(":")[-1].strip().split()
                meta["coefficients"] = [float(x) for x in raw_vals]
                
    except Exception as e:
        print(f"⚠️ Error reading manifest {os.path.basename(txt_filepath)}: {e}")
        
    return meta


def organize_incoming_files():
    """
    Sorts files from INBOX into the hierarchy: DATA_ROOT / Date / Plant_ID / Sensor_Type
    Implements specific logic for prefixes 'Spectral', 'Multispectral', 'Thermal'.
    """
    print("\n--- 1. Sorting incoming files (INBOX) ---")
    if not os.path.exists(PATH_INBOX): 
        print(f"⚠️ Inbox directory not found: {PATH_INBOX}")
        return

    count = 0
    # Reserved keywords that cannot be Plant IDs
    RESERVED_KEYWORDS = ["SPECTRAL", "MULTISPECTRAL", "THERMAL"]

    for filename in os.listdir(PATH_INBOX):
        file_path = os.path.join(PATH_INBOX, filename)
        if os.path.isdir(file_path): continue

        # Init variables
        plant_id = "Unassigned"
        sensor_type = "Unclassified"
        filename_clean = filename.strip()
        
        # --- RULE 1: EXPLICIT PREFIX DETECTION ---
        # Check if file starts with specific keywords followed by a separator (e.g., "_")
        # Regex looks for: (Spectral|Thermal) _ (PotentialID) _ (Rest)
        match_explicit = re.match(r"^(Spectral|Multispectral|Thermal)_([a-zA-Z0-9]+)_(.*)", filename_clean, re.IGNORECASE)
        
        if match_explicit:
            type_str = match_explicit.group(1).upper()
            candidate_id = match_explicit.group(2)
            
            # 1.1 Determine Sensor Type
            if "THERMAL" in type_str:
                sensor_type = "Thermal"
            else:
                sensor_type = "Spectral"
                
            # 1.2 Validate Plant ID
            # Rule: Must not be a reserved word AND must start with a letter
            if candidate_id.upper() not in RESERVED_KEYWORDS and candidate_id[0].isalpha():
                plant_id = candidate_id
            else:
                plant_id = "Unassigned"
                
        else:
            # --- RULE 2: FALLBACK PATTERN DETECTION ---
            # If no explicit prefix, try to guess based on file structure
            
            # Case A: Thermal (Starts with digits like "00-10-12...")
            # Also checks for thermal keywords if the pattern matches
            if re.match(r"^(\d{2}-\d{2}-\d{2}-\d{3})", filename_clean):
                sensor_type = "Thermal"
                print(f"   [Ingestion] Pattern Detection used: Thermal Digit Pattern detected for {filename}")
                plant_id = "Unassigned" # Thermal files usually don't have the ID in the name here
                 
            # Case B: Spectral (Contains Date_Time pattern OR ends with specific extensions)
            elif re.search(r"_\d{8}_\d{6}_", filename_clean) or filename_clean.lower().endswith(('_raw.tiff', '.txt')):
                sensor_type = "Spectral"
                print(f"   [Ingestion] Pattern Detection used: Spectral Date/Time Pattern detected for {filename}")
                
                # Try to extract Plant ID from the start of the file
                # Split by first underscore
                parts = filename_clean.split('_')
                if len(parts) > 1:
                    candidate = parts[0]
                    # Same validation rules
                    if candidate.upper() not in RESERVED_KEYWORDS and candidate[0].isalpha():
                        plant_id = candidate
                    else:
                        plant_id = "Unassigned"

        print(f"   [Ingestion] File: {filename} -> Detected Type: {sensor_type}, Plant: {plant_id}")

        # --- PROCESSING & MOVING ---
        
        # Filter: Delete Thermal Screenshots
        if sensor_type == "Thermal" and "screenshot" in filename_clean.lower():
            try:
                os.remove(file_path)
                print(f"🗑️ Deleted screenshot: {filename}")
            except Exception as e:
                print(f"⚠️ Could not delete {filename}: {e}")
            continue
            
        # Move Valid Files
        if sensor_type != "Unclassified":
            try:
                timestamp = os.path.getmtime(file_path)
                date_folder = datetime.fromtimestamp(timestamp).strftime('%Y-%m-%d')
                
                # Target: DATA / Date / PlantID / SensorType
                target_dir = os.path.join(PATH_DATA_ROOT, date_folder, plant_id, sensor_type)
                os.makedirs(target_dir, exist_ok=True)
                
                target_path = os.path.join(target_dir, filename)
                if not os.path.exists(target_path):
                    shutil.move(file_path, target_path)
                    count += 1
                    print(f"📦 Moved: {filename} -> {plant_id}/{sensor_type}")
                else:
                    print(f"ℹ️ Skipped (Duplicate): {filename}")
            except Exception as e:
                print(f"❌ Error moving {filename}: {e}")
        else:
            print(f"⚠️ Skipped Unclassified file: {filename}")

    print(f"   -> {count} files successfully organized.")

def process_spectral_image(filepath, manifest_meta):
    img_data = tiff.imread(filepath)
    h, w = img_data.shape
    print(f"   [Processing] Loaded Raw TIFF. Dimensions: {w}x{h} pixels.")
    new_h, new_w = h // 4, w // 4
    
    # Retrieve dynamic info from the text file
    # If the text file was missing, use default values
    real_wavelengths = manifest_meta.get("wavelengths")
    if not real_wavelengths or len(real_wavelengths) != 10:
        real_wavelengths = [411, 463, 500, 557, 606, 667, 694, 756, 808, 870] # Fallback
        
    coeffs = manifest_meta.get("coefficients")
    if not coeffs or len(coeffs) != 10:
        coeffs = [1.0] * 10 # No correction if file is missing
        
    cube = np.zeros((10, new_h, new_w), dtype=np.float32)
    analytics = {}
    print(f"   [Processing] Applied Normalization Coefficients: {coeffs}")
    
    for band_idx, coords in TOUCAN_PATTERN.items():
        # 1. Reconstruction (Demosaicing)
        stack = [img_data[r::4, c::4][:new_h, :new_w] for r, c in coords]
        raw_band = np.mean(stack, axis=0)
        
        # 2. Radiometric Correction (Applying the coefficient)
        # This is the crucial step: normalizing the intensity
        corrected_band = raw_band * coeffs[band_idx]
        
        # Store in the cube
        cube[band_idx] = corrected_band

        # 3. Histogram Calculation on the CORRECTED band
        # Use the real name (e.g., "411nm" not "410nm")
        band_name = f"{real_wavelengths[band_idx]}nm"
        
        # Round for the histogram because coefficients create decimals
        hist, _ = np.histogram(corrected_band.astype(np.uint16), bins=256)
        
        analytics[band_name] = {
            "histogram": hist.tolist(),
            "correction_factor": coeffs[band_idx] # Store the factor used
        }
        
    print(f"   [Processing] Signal Stats -> Min: {np.min(cube):.2f}, Max: {np.max(cube):.2f}, Mean: {np.mean(cube):.2f}")
    return {
        "camera_model": "SILIOS TOUCAN",
        "cube": cube,
        "camera_sn": manifest_meta.get("camera_sn", "Unknown"),
        "exposure_ms": manifest_meta.get("exposure"),
        "analytics": analytics
    }

def rename_batch_prefix(folder_path, old_prefix, new_prefix):
    """
    Batch renames all files in a folder that start with 'old_prefix',
    replacing that start with 'new_prefix'.
    
    Example: 
    rename_batch_prefix("C:/INBOX", "hbda", "PLANT1")
    will transform "hbda.0001.tiff" into "PLANT1.0001.tiff"
    """
    
    # 1. Folder verification
    if not os.path.exists(folder_path):
        print(f"❌ Folder does not exist: {folder_path}")
        return

    print(f"🔄 Renaming in progress in {folder_path}...")
    print(f"   Replacing '{old_prefix}' with '{new_prefix}'")
    
    count = 0
    errors = 0

    # 2. Iterate through files
    for filename in os.listdir(folder_path):
        # Process only files starting with the old prefix
        if filename.startswith(old_prefix):
            
            # Construct the new filename
            # Cut the "old_prefix" part and paste "new_prefix" at the start
            suffix = filename[len(old_prefix):] # The rest of the name (e.g., ".0001.tiff")
            new_filename = new_prefix + suffix
            
            old_path = os.path.join(folder_path, filename)
            new_path = os.path.join(folder_path, new_filename)
            
            try:
                # Safety check: do not overwrite if the file already exists
                if os.path.exists(new_path):
                    print(f"⚠️ Skipped (Already exists): {new_filename}")
                    errors += 1
                    continue
                
                # Actual renaming
                os.rename(old_path, new_path)
                print(f"✅ {filename} -> {new_filename}")
                count += 1
                
            except Exception as e:
                print(f"❌ Error on {filename}: {e}")
                errors += 1

    print(f"\n--- Finished: {count} files renamed ({errors} errors) ---")


def prepare_hyperspectral_data(raw_hdr_path, dark_hdr_path, white_hdr_path, background='darken', min_brightness=0.03, max_brightness=0.85, ndvi_threshold=-0.1):
    """
    Version optimisée pour la MÉMOIRE (RAM) et la RAPIDITÉ.
    Empêche les crashs Jupyter sur les gros fichiers de 224 bandes.
    """
    print("⏳ [1/4] Chargement des références (Optimisation RAM)...")
    
    # 1. Chargement et purge immédiate des références pour libérer la RAM
    dark_img = envi.open(dark_hdr_path)
    dark_cube = np.array(dark_img[:, :, :], dtype=np.float32)
    dark_profile = np.mean(dark_cube, axis=0)
    del dark_cube  # Détruit le cube noir de la mémoire
    gc.collect()   # Force le nettoyage
    
    white_img = envi.open(white_hdr_path)
    white_cube = np.array(white_img[:, :, :], dtype=np.float32)
    white_profile = np.mean(white_cube, axis=0)
    del white_cube # Détruit le cube blanc de la mémoire
    gc.collect()

    # Dénominateur pour la calibration
    denominator = (white_profile - dark_profile)
    denominator[denominator == 0] = 1e-6
    
    
    print("⏳ [2/4] Chargement du fichier RAW et Calibration In-Place...")
    # 2. On charge l'image principale en forçant un format léger (float32)
    raw_img = envi.open(raw_hdr_path)
    reflectance_cube = np.array(raw_img[:, :, :], dtype=np.float32)
    
    # OPÉRATIONS "IN-PLACE" : Modifie le tableau existant (économise ~3 Go de RAM !)
    reflectance_cube -= dark_profile
    reflectance_cube /= denominator
    np.clip(reflectance_cube, 0, 1, out=reflectance_cube)
    
    print("🌿 [3/4] Création du masque...")
    
    try:
        wavelengths = np.array(raw_img.metadata['wavelength'], dtype=float)
        xlabel = "Wavelength (nm)"
        band_nir = (np.abs(wavelengths - 840.0)).argmin()
        band_red = (np.abs(wavelengths - 650.0)).argmin()
        idx_vis_start = (np.abs(wavelengths - 400.0)).argmin()
        idx_vis_end = (np.abs(wavelengths - 700.0)).argmin()
    except KeyError:
        wavelengths = np.arange(reflectance_cube.shape[2])
        xlabel = "Spectral Band Number"
        band_nir, band_red = 162, 95
        idx_vis_start, idx_vis_end = 0, 110 
        
    # --- MASQUES LÉGERS ---
    brightness_visible = np.mean(reflectance_cube[:, :, idx_vis_start:idx_vis_end], axis=2)
    masque_luminosite = (brightness_visible > min_brightness) & (brightness_visible < max_brightness)
    del brightness_visible # Nettoyage
    
    band_nir_data = reflectance_cube[:, :, band_nir]
    band_red_data = reflectance_cube[:, :, band_red]
    ndvi = (band_nir_data - band_red_data) / (band_nir_data + band_red_data + 1e-6)
    masque_ndvi = ndvi > ndvi_threshold 
    del band_nir_data, band_red_data, ndvi # Nettoyage
    
    masque_plante = masque_luminosite & masque_ndvi
    del masque_luminosite, masque_ndvi
    
    pixels_plante = reflectance_cube[masque_plante]
    if len(pixels_plante) == 0:
        print("⚠️ Aucune plante détectée. Ajustez les seuils.")
        return None

    print("📊 [4/4] Extraction des signatures et Préparation visuelle...")
    spectre_moyen = np.mean(pixels_plante, axis=0)
    spectre_std = np.std(pixels_plante, axis=0)

    rgb_image = reflectance_cube[:, :, [110, 70, 30]].copy()
    min_val = np.percentile(rgb_image, 2)
    max_val = np.percentile(rgb_image, 98)
    rgb_image = np.clip((rgb_image - min_val) / (max_val - min_val), 0, 1)

    if background == 'darken':
        
        rgb_image[~masque_plante] = rgb_image[~masque_plante] * 0.15
    elif background == 'purple':
        rgb_image[~masque_plante] = [0.6, 0.0, 0.8]
        
    rgb_final = np.rot90(rgb_image, k=1)

    print("✅ Données prêtes !")
    
    return {
        "rgb": rgb_final,
        "wavelengths": wavelengths,
        "mean": spectre_moyen,
        "std": spectre_std,
        "xlabel": xlabel,
        "cube": reflectance_cube, # Maintenant 2x plus léger !
        "masque": masque_plante
    }

def separate_data(donnees, ligne_coupe):
    """
    Sépare un jeu de données hyperspectrales en deux le long de l'axe de balayage (lignes).
    Recalcule les spectres moyens et les images RGB pour chaque partie.
    """
    if donnees is None:
        print("⚠️ Aucune donnée à séparer.")
        return None, None

    print(f"✂️ Découpage du cube à la ligne {ligne_coupe}...")

    # Récupération des données du dictionnaire
    cube_complet = donnees["cube"]
    masque_complet = donnees["masque"]
    wavelengths = donnees["wavelengths"]
    xlabel = donnees.get("xlabel", "Longueur d'onde (nm)")
    
    # L'image RGB qui a DÉJÀ votre fond (elle est actuellement tournée à 90°)
    rgb_complet_tourne = donnees["rgb"] 

    # 1. On annule temporairement la rotation (k=-1) pour l'aligner avec le cube et le masque
    rgb_complet = np.rot90(rgb_complet_tourne, k=-1)

    # ==========================================
    # SET 1 : Du début (0) jusqu'à la ligne_coupe
    # ==========================================
    cube_1 = cube_complet[:ligne_coupe, :, :]
    masque_1 = masque_complet[:ligne_coupe, :]
    rgb_1 = rgb_complet[:ligne_coupe, :, :]
    
    # On retourne le morceau obtenu (k=1) pour l'affichage final
    rgb_final_1 = np.rot90(rgb_1, k=1)

    # Recalcul des spectres (uniquement sur les pixels de la plante 1)
    pixels_1 = cube_1[masque_1]
    moyen_1 = np.mean(pixels_1, axis=0) if len(pixels_1) > 0 else np.zeros_like(wavelengths)
    std_1 = np.std(pixels_1, axis=0) if len(pixels_1) > 0 else np.zeros_like(wavelengths)

    donnees_1 = {
        "cube": cube_1,
        "masque": masque_1,
        "rgb": rgb_final_1,
        "wavelengths": wavelengths,
        "mean": moyen_1,
        "std": std_1,
        "xlabel": xlabel
    }

    # ==========================================
    # SET 2 : De la ligne_coupe jusqu'à la fin
    # ==========================================
    cube_2 = cube_complet[ligne_coupe:, :, :]
    masque_2 = masque_complet[ligne_coupe:, :]
    rgb_2 = rgb_complet[ligne_coupe:, :, :]
    
    # On retourne le morceau obtenu (k=1) pour l'affichage final
    rgb_final_2 = np.rot90(rgb_2, k=1)

    # Recalcul des spectres (uniquement sur les pixels de la plante 2)
    pixels_2 = cube_2[masque_2]
    moyen_2 = np.mean(pixels_2, axis=0) if len(pixels_2) > 0 else np.zeros_like(wavelengths)
    std_2 = np.std(pixels_2, axis=0) if len(pixels_2) > 0 else np.zeros_like(wavelengths)

    donnees_2 = {
        "cube": cube_2,
        "masque": masque_2,
        "rgb": rgb_final_2,
        "wavelengths": wavelengths,
        "mean": moyen_2,
        "std": std_2,
        "xlabel": xlabel
    }
    print("✅ Découpage terminé ! Deux sets de données créés.")
    return donnees_1, donnees_2


# --- MAIN PIPELINE FUNCTION ---
def run_pipeline():
    # A. Ingestion (Organization)
    organize_incoming_files()
    
    # B. Database Connection
    client = get_mongo_client()
    if not client: return
    
    db = client[DB_NAME]
    fs = gridfs.GridFS(db)

    print("\n--- 2. Scientific Processing ---")
    
    for root, dirs, files in os.walk(PATH_DATA_ROOT):
        if os.path.basename(root) not in ["Spectral", "Hyperspectral", "Thermal"]: continue
        
        manifest_meta = {}
        txt_files = [f for f in files if f.endswith(".txt")]
        if txt_files:
            manifest_meta = parse_colorshades_manifest(os.path.join(root, txt_files[0]))

        for file in files:
            
            # =========================================================================
            # HYPERSPECTRAL BLOCK (.hdr / .raw)
            # =========================================================================
            if file.endswith(".hdr") and "DARKREF" not in file and "WHITEREF" not in file:
                
                if db["sensors_hyperspectral"].count_documents({"filename": file}) > 0:
                    continue

                print(f"⚙️ Processing Hyperspectral: {file}")
                filepath = os.path.join(root, file)
                
                try:
                    plant_id = os.path.basename(os.path.dirname(root)) 
                    timestamp = datetime.fromtimestamp(os.path.getmtime(filepath))
                    
                    fichiers_dark = glob.glob(os.path.join(root, "*DARKREF*.hdr"))
                    fichiers_white = glob.glob(os.path.join(root, "*WHITEREF*.hdr"))
                    
                    if fichiers_dark and fichiers_white:
                        specim_meta = prepare_hyperspectral_data(filepath, fichiers_dark[0], fichiers_white[0])
                        if specim_meta is None: continue
                            
                        raw_filepath = filepath.replace(".hdr", ".raw")
                        if not os.path.exists(raw_filepath): raw_filepath = filepath.replace(".hdr", ".img")
                            
                        print(f"   [Storage] Uploading Hyperspectral cube to GridFS...")
                        with open(raw_filepath, 'rb') as f:
                            cube_file_id = fs.put(f, filename=os.path.basename(raw_filepath))
                        
                        # 🟢 1. Link to or create the Central Capture Event
                        event_id = get_or_create_capture_event(db, plant_id, timestamp)
                        
                        # 🟢 2. Build the specific Hyperspectral Document
                        hs_doc = {
                            "capture_event_id": event_id,
                            "gridfs_ref": cube_file_id, 
                            "captured_at": timestamp,
                            "filename": file,
                            "spectral_range_nm": specim_meta.get("wavelengths", []),
                            "mean_signature": specim_meta.get("mean", [])
                        }
                        
                        db["sensors_hyperspectral"].insert_one(sanitize_for_mongo(hs_doc))
                        print(f"✅ [Success] Hyperspectral linked to Event ID: {event_id}")
                        
                except Exception as e:
                    print(f"   ❌ Error processing hyperspectral {file}: {e}")

            # =========================================================================
            # MULTISPECTRAL & THERMAL BLOCK (.tiff)
            # =========================================================================
            elif file.endswith("_raw.tiff"):
                
                if db["sensors_multispectral"].count_documents({"filename": file}) > 0:
                    continue

                print(f"⚙️ Processing Multispectral: {file}")
                filepath = os.path.join(root, file)
                
                try:
                    plant_id = os.path.basename(os.path.dirname(root)) 
                    timestamp = datetime.fromtimestamp(os.path.getmtime(filepath))
                    
                    raw_spec_data = process_spectral_image(filepath, manifest_meta)
                    spec_data = sanitize_for_mongo(raw_spec_data)
                    
                    thermal_files = find_thermal_cluster(filepath, plant_id=plant_id)
                    thermal_files_ids = []
                    
                    print(f"   [Storage] Uploading files to GridFS...")
                    with open(filepath, 'rb') as f:
                        ms_file_id = fs.put(f, filename=file)
                    
                    for key, t_path in thermal_files.items():
                        with open(t_path, 'rb') as f:
                            thermal_files_ids.append(fs.put(f, filename=os.path.basename(t_path)))

                    # 🟢 1. Link to or create the Central Capture Event
                    # 🟢 1. Link to or create the Central Capture Event
                    event_id = get_or_create_capture_event(db, plant_id, timestamp)

                    # 🟢 2. Build and insert the Multispectral Document (Strict PDF Schema)
                    # On suppose que 'spec_data' contient 'ndvi' et 'histogram'
                    ms_doc = {
                        "capture_event_id": event_id,
                        "gridfs_ref": ms_file_id,
                        "captured_at": timestamp,
                        "filename": file,
                        "integration_time_ms": manifest_meta.get('exposure', None),
                        "ndvi": spec_data.get('ndvi', None), # Extrait de ton dictionnaire
                        "histogram_256": spec_data.get('histogram_256', []) # Extrait de ton dictionnaire
                    }
                    db["sensors_multispectral"].insert_one(sanitize_for_mongo(ms_doc))
                    
                    # 🟢 3. Build and insert the Thermal Document
                    if thermal_files:
                        th_doc = {
                            "capture_event_id": event_id,
                            "gridfs_ref": thermal_files_ids,
                            "captured_at": timestamp,
                            # Ajout des champs demandés par le PDF. 
                            # Si tu n'as pas encore la fonction pour les lire, on met None.
                            "ambient_temp_c": None, 
                            "max_leaf_temp_c": None,
                            "cwsi": None 
                        }
                        db["sensors_thermal"].insert_one(sanitize_for_mongo(th_doc))

                    # 🟢 4. INITIALISATION ML_ANALYSIS (Optionnel mais recommandé)
                    # Crée une entrée "pending" pour que ton modèle IA sache qu'il y a du travail !
                    if db["ml_analysis"].count_documents({"capture_event_id": event_id}) == 0:
                        ml_doc = {
                            "capture_event_id": event_id,
                            "health_status": "pending",
                            "confidence_scores_decision_tree": None,
                            "confidence_scores_logistic_reg": None,
                            "confidence_scores_neural_net": None,
                            "analyzed_at": None
                        }
                        db["ml_analysis"].insert_one(ml_doc)

                    print(f"✅ [Success] MS/Thermal & ML Init linked to Event ID: {event_id}")

                except Exception as e:
                    print(f"   ❌ Error processing {file}: {e}")
            # =========================================================================
            # INDEPENDENT THERMAL BLOCK
            # =========================================================================
            # Catch thermal files (adjust the extension if your Workswell uses .jpg or .csv)
            # =========================================================================
            # INDEPENDENT THERMAL BLOCK
            # =========================================================================
            # 🟢 FIX: .lower() makes it case-insensitive to catch .TIFF, .TIF, or .tiff
            elif file.lower().endswith((".tiff", ".tif")) and not file.endswith("_raw.tiff") and "spectral" not in file.lower():
                
                # Anti-Duplicate Check
                if db["sensors_thermal"].count_documents({"filename": file}) > 0:
                    continue

                print(f"⚙️ Processing Independent Thermal: {file}")
                filepath = os.path.join(root, file)
                
                try:
                    plant_id = os.path.basename(os.path.dirname(root)) 
                    timestamp = datetime.fromtimestamp(os.path.getmtime(filepath))
                    
                    print(f"   [Storage] Uploading Thermal file to GridFS...")
                    with open(filepath, 'rb') as f:
                        t_file_id = fs.put(f, filename=file)

                    # 1. Link to or create the Central Capture Event 
                    event_id = get_or_create_capture_event(db, plant_id, timestamp)

                    # 2. Build and insert the Thermal Document
                    th_doc = {
                        "capture_event_id": event_id,
                        "gridfs_ref": [t_file_id], 
                        "captured_at": timestamp,
                        "filename": file,          
                        "camera_model": "WORKSWELL WIRIS AGRO R",
                        "ambient_temp_c": None,
                        "max_leaf_temp_c": None,
                        "cwsi": None 
                    }
                    db["sensors_thermal"].insert_one(sanitize_for_mongo(th_doc))

                    # 3. INITIALISATION ML_ANALYSIS
                    if db["ml_analysis"].count_documents({"capture_event_id": event_id}) == 0:
                        ml_doc = {
                            "capture_event_id": event_id,
                            "health_status": "pending",
                            "confidence_scores_decision_tree": None,
                            "confidence_scores_logistic_reg": None,
                            "confidence_scores_neural_net": None,
                            "analyzed_at": None
                        }
                        db["ml_analysis"].insert_one(ml_doc)

                    print(f"✅ [Success] Independent Thermal linked to Event ID: {event_id}")

                except Exception as e:
                    print(f"   ❌ Error processing thermal {file}: {e}")
                    
    print("\n✅ Pipeline execution complete.")



def export_analysis_to_csv(filepath, output_csv="data_export.csv", analysis_type="profile", bins=256):
    """
    Master function to export analysis data to CSV for Excel/Stats.
    
    Parameters:
    - filepath: Path to the TIFF file.
    - output_csv: Filename for the saved CSV.
    - analysis_type: 
        * 'profile'   -> Exports Mean Intensity vs Wavelength (The Curve).
        * 'histogram' -> Exports Pixel Counts vs Intensity for all bands (The Distribution).
    - bins: Number of bins (only used if type is 'histogram').
    """
    if not os.path.exists(filepath):
        return

    img_data = tiff.imread(filepath)
    data_dict = {} 
    
    try:
        is_125_bands = (img_data.ndim == 3 and img_data.shape[2] == 125)
        is_external = img_data.ndim == 3 and img_data.shape[2] > 1 and img_data.shape[2] > img_data.shape[0]
        num_bands = img_data.shape[2] if is_external else (img_data.shape[0] if img_data.ndim == 3 else 10)

        if analysis_type == "profile":
            wavelengths = []
            intensities = []

            for i in range(num_bands):
                # Remplissage X (Wavelengths)
                if is_125_bands:
                    wavelengths.append(round(450 + i * (500 / 124), 2))
                else:
                    wavelengths.append(int(SILIOS_WAVELENGTHS.get(i, f"{400+i*5}nm").replace("nm", "")))
                
                # Remplissage Y (Intensities)
                if is_external:
                    intensities.append(np.mean(img_data[:, :, i]))
                elif img_data.ndim == 3:
                    intensities.append(np.mean(img_data[i]))
                else:
                    r_off, c_off = i // 4, i % 4
                    intensities.append(np.mean(img_data[r_off::4, c_off::4]))
            
            data_dict["Wavelength_nm"] = wavelengths
            data_dict["Mean_Intensity"] = intensities
            
        elif analysis_type == "histogram":
            max_val = np.max(img_data)
            bin_edges = np.linspace(0, max_val, bins + 1)
            data_dict["Bin_Start_Value"] = bin_edges[:-1]
            
            for i in range(num_bands):
                if is_125_bands:
                    band_name = f"{450 + i * (500 / 124):.1f}nm"
                else:
                    band_name = SILIOS_WAVELENGTHS.get(i, f"Band_{i}")
                
                if is_external:
                    pixels = img_data[:, :, i].flatten()
                elif img_data.ndim == 3:
                    pixels = img_data[i].flatten()
                else:
                    r_off, c_off = i // 4, i % 4
                    pixels = img_data[r_off::4, c_off::4].flatten()
                
                counts, _ = np.histogram(pixels, bins=bin_edges)
                data_dict[f"Count_{band_name}"] = counts

        df = pd.DataFrame(data_dict)
        df.to_csv(output_csv, index=False)
        print(f"✅ Success! Data saved to: {output_csv}")
        return df

    except Exception as e:
        print(f"❌ Error during export: {e}")

